#!/usr/bin/env bash

# Install nginx
apt-get update -y
apt-get install nginx -y

# Configure nginx to listen on port 80
sed -i 's/^.*listen\s*80\s*;.*$/\tlisten 80;/g' /etc/nginx/sites-available/default

# Configure nginx to return "Holberton School" on root GET request
echo 'server {
    listen 80;
    server_name _;

    location / {
        return 200 "Holberton School for the win!\n";
    }
}' > /etc/nginx/sites-available/holberton

# Enable the new site configuration
ln -s /etc/nginx/sites-available/holberton /etc/nginx/sites-enabled/

# Restart nginx
service nginx restart
